version: '3.7'
services:
  ptu12_library:
    build: .
    image: python:ptu12_library
    container_name: ptu12_library.dev
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./ptu12_library:/app
    depends_on:
      - db
    links:
      - db:postgres
    command: >
      bash -c "python wait_for_postgres.py &&
               python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn ptu12_library.wsgi --bind 0.0.0.0:8000"
  db:
    image: postgres
    container_name: ptu12_library.db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    env_file:
      - .env
  nginx:
    build: ./nginx/.
    image: nginx:ptu12_library
    container_name: ptu12_library.nginx
    restart: always
    ports:
      - 80:80
    links:
      - ptu12_library:ptu12_library
    volumes:
      - ./ptu12_library/media:/app/media
      - ./ptu12_library/static:/app/static
